name:                git-haskell
version:             0.1.0.0
github:              "josephsumabat/git-haskell"
license:             BSD3
author:              "Joseph Sumabat"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/git-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- cryptohash-sha1
- directory
- filepath
- megaparsec
- ordered-containers
- split
- text
- transformers
- utf8-string
- zlib


library:
  source-dirs: src

executables:
  git-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - git-haskell

tests:
  git-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-haskell
